on:
  push:
    tags:
      - 'v*'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: tag
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Configure GitHub Packages NuGet source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        --name github \
        --username x-access-token \
        --password ${{ secrets.GITHUB_TOKEN }} \
        --store-password-in-clear-text
      
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish container to GHCR
      run: |
        dotnet publish /t:PublishContainer --os linux --arch x64 \
          -p "ContainerImageTags=latest;${{ steps.tag.outputs.version }}"\
          -p ContainerRegistry=ghcr.io \
          -p ContainerRepository=${{ github.repository }}
